name: CD

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Build & publish
      run: dotnet publish LightBulb/ -o PublishOutput/ --configuration Release

    - name: Pack (archive)
      run: Compress-Archive -Path PublishOutput/* -DestinationPath PublishOutput/Archive.zip -Force
      shell: pwsh

    - name: Pack (installer)
      run: |
        choco install innosetup --no-progress
        dotnet publish LightBulb/ -o Installer/Source/ --configuration Release
        & "c:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer/Installer.iss
      shell: pwsh

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload release artifact (archive)
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: PublishOutput/Archive.zip
        asset_name: LightBulb.zip
        asset_content_type: application/zip

    - name: Upload release artifact (installer)
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Installer/bin/LightBulb-Installer.exe
        asset_name: LightBulb-Installer.exe
        asset_content_type: application/octet-stream
